"""
PaperMind AI - PDF Export Service

Generates print-ready question paper and answer key PDFs from persisted
MongoDB paper records. No AI calls or uploaded file reads happen here.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
import re

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

UNIVERSITY_NAME = "KR MANGALAM UNIVERSITY"
PLACEHOLDER = "To be specified"
FOOTER_TEXT = "Generated by PaperMind AI"


@dataclass(frozen=True)
class ExportMetadata:
    """Printable paper metadata with clean placeholders."""

    department: str
    course_code: str
    semester: str
    exam_type: str
    duration: str
    exam_date: str
    instructions: str


def generate_question_paper_pdf(
    *,
    paper: dict,
    metadata_overrides: dict[str, str | None] | None = None,
) -> bytes:
    """Return a print-ready question paper PDF as bytes."""
    metadata = _build_metadata(paper, metadata_overrides)
    buffer = BytesIO()
    doc = _build_document(buffer, title=_safe_filename(paper.get("title", "Question Paper")))
    story = _build_header(paper=paper, metadata=metadata, answer_key=False)
    story.extend(_build_instruction_block(metadata.instructions))
    story.append(Spacer(1, 0.28 * cm))

    for index, question in enumerate(paper.get("questions", []), start=1):
        story.extend(_build_question_flowable(index=index, question=question, include_answer=False))

    doc.build(
        story,
        onFirstPage=lambda canvas, document: _draw_footer(canvas, document),
        onLaterPages=lambda canvas, document: _draw_footer(canvas, document),
    )
    return buffer.getvalue()


def generate_answer_key_pdf(
    *,
    paper: dict,
    metadata_overrides: dict[str, str | None] | None = None,
) -> bytes:
    """Return a faculty answer key PDF as bytes."""
    metadata = _build_metadata(paper, metadata_overrides)
    buffer = BytesIO()
    doc = _build_document(buffer, title=_safe_filename(f"{paper.get('title', 'Question Paper')} Answer Key"))
    story = _build_header(paper=paper, metadata=metadata, answer_key=True)
    story.append(_paragraph("Faculty answer key. Do not distribute to students.", "Warning"))
    story.append(Spacer(1, 0.28 * cm))

    for index, question in enumerate(paper.get("questions", []), start=1):
        story.extend(_build_question_flowable(index=index, question=question, include_answer=True))

    doc.build(
        story,
        onFirstPage=lambda canvas, document: _draw_footer(canvas, document),
        onLaterPages=lambda canvas, document: _draw_footer(canvas, document),
    )
    return buffer.getvalue()


def build_answer_payload(paper: dict) -> dict:
    """Build the API response for the in-app answer view."""
    return {
        "paper_id": str(paper.get("_id") or paper.get("id")),
        "title": paper.get("title", ""),
        "subject": paper.get("subject", ""),
        "exam_name": paper.get("exam_name"),
        "total_marks": paper.get("total_marks", 0),
        "total_questions": paper.get("total_questions", len(paper.get("questions", []))),
        "answers": [
            {
                "question_id": question.get("id", ""),
                "number": index,
                "question_text": question.get("question_text", ""),
                "answer": question.get("answer", ""),
                "explanation": question.get("explanation", ""),
                "bloom_level": question.get("bloom_level", ""),
                "difficulty": question.get("difficulty", ""),
                "marks": question.get("marks", 0),
                "question_type": question.get("question_type", ""),
                "source_chunk": question.get("source_chunk", 0),
                "confidence_score": question.get("confidence_score", 0.0),
                "options": question.get("options", []),
            }
            for index, question in enumerate(paper.get("questions", []), start=1)
        ],
    }


def _build_document(buffer: BytesIO, *, title: str) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.65 * cm,
        leftMargin=1.65 * cm,
        topMargin=1.35 * cm,
        bottomMargin=1.5 * cm,
        title=title,
        author="PaperMind AI",
    )


def _build_metadata(
    paper: dict,
    overrides: dict[str, str | None] | None,
) -> ExportMetadata:
    configuration = paper.get("configuration", {}) or {}
    export_metadata = configuration.get("export_metadata", {}) or {}
    overrides = overrides or {}

    def pick(key: str, fallback: str | None = None) -> str:
        value = overrides.get(key) or export_metadata.get(key) or fallback
        return _clean_text(value) or PLACEHOLDER

    generated_at = _format_date(paper.get("generated_at") or paper.get("created_at"))
    instructions = (
        overrides.get("instructions")
        or configuration.get("instructions")
        or "Answer all questions. Marks are indicated against each question. Write clearly and justify answers where required."
    )

    return ExportMetadata(
        department=pick("department"),
        course_code=pick("course_code"),
        semester=pick("semester"),
        exam_type=pick("exam_type", paper.get("exam_name") or "Examination"),
        duration=pick("duration"),
        exam_date=pick("exam_date", generated_at),
        instructions=_clean_text(instructions),
    )


def _build_header(*, paper: dict, metadata: ExportMetadata, answer_key: bool) -> list:
    title = _clean_text(paper.get("title")) or "Question Paper"
    subject = _clean_text(paper.get("subject")) or PLACEHOLDER
    max_marks = str(paper.get("total_marks", PLACEHOLDER))
    subtitle = "Faculty Answer Key" if answer_key else "Question Paper"

    data = [
        ["Department", metadata.department, "Course Code", metadata.course_code],
        ["Subject", subject, "Semester", metadata.semester],
        ["Examination", metadata.exam_type, "Duration", metadata.duration],
        ["Maximum Marks", max_marks, "Date", metadata.exam_date],
    ]

    return [
        _paragraph(UNIVERSITY_NAME, "University"),
        _paragraph(subtitle.upper(), "Subtitle"),
        Spacer(1, 0.15 * cm),
        _paragraph(title, "PaperTitle"),
        Spacer(1, 0.25 * cm),
        _metadata_table(data),
        Spacer(1, 0.35 * cm),
    ]


def _build_instruction_block(instructions: str) -> list:
    items = [item.strip() for item in re.split(r"[\n;]+", instructions or "") if item.strip()]
    if not items:
        items = ["Answer all questions.", "Marks are indicated against each question."]
    return [
        _paragraph("Instructions", "SectionHeading"),
        ListFlowable(
            [ListItem(_paragraph(item, "Instruction"), leftIndent=8) for item in items],
            bulletType="1",
            leftIndent=14,
            bulletFontSize=8.5,
        ),
    ]


def _build_question_flowable(*, index: int, question: dict, include_answer: bool) -> list:
    marks = question.get("marks", 0)
    question_text = _clean_text(question.get("question_text")) or "Question text unavailable."
    meta = " | ".join(
        part
        for part in [
            _label(question.get("question_type")),
            _label(question.get("bloom_level")),
            _label(question.get("difficulty")),
        ]
        if part
    )
    header = Table(
        [[_paragraph(f"Q{index}.", "QuestionNumber"), _paragraph(question_text, "Question"), _paragraph(f"[{marks}]", "Marks")]],
        colWidths=[1.1 * cm, 14.1 * cm, 1.4 * cm],
    )
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )

    block = [header]
    options = [str(option) for option in question.get("options", []) if str(option).strip()]
    if options:
        block.append(Spacer(1, 0.08 * cm))
        block.append(
            ListFlowable(
                [ListItem(_paragraph(option, "Option"), leftIndent=8) for option in options],
                bulletType="a",
                leftIndent=1.25 * cm,
                bulletFontSize=8.5,
            )
        )
    if meta:
        block.append(_paragraph(meta, "QuestionMeta"))

    if include_answer:
        block.append(Spacer(1, 0.08 * cm))
        block.append(_paragraph("Answer", "AnswerLabel"))
        block.append(_paragraph(_clean_text(question.get("answer")) or "Answer unavailable.", "Answer"))
        explanation = _clean_text(question.get("explanation"))
        if explanation:
            block.append(_paragraph(f"Explanation: {explanation}", "Explanation"))
        confidence = question.get("confidence_score")
        if confidence is not None:
            block.append(_paragraph(f"Confidence: {float(confidence):.2f}", "QuestionMeta"))

    block.append(Spacer(1, 0.28 * cm))
    return block


def _metadata_table(data: list[list[str]]) -> Table:
    table_data = []
    for row in data:
        table_data.append([
            _paragraph(row[0], "MetaLabel"),
            _paragraph(row[1], "MetaValue"),
            _paragraph(row[2], "MetaLabel"),
            _paragraph(row[3], "MetaValue"),
        ])
    table = Table(table_data, colWidths=[2.65 * cm, 5.65 * cm, 2.8 * cm, 5.5 * cm])
    table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#B8BDC8")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F5F8")),
                ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F3F5F8")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return table


def _draw_footer(canvas, document) -> None:
    canvas.saveState()
    width, _ = A4
    canvas.setStrokeColor(colors.HexColor("#D5DAE3"))
    canvas.line(document.leftMargin, 1.05 * cm, width - document.rightMargin, 1.05 * cm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#5F6673"))
    canvas.drawString(document.leftMargin, 0.68 * cm, FOOTER_TEXT)
    canvas.drawRightString(width - document.rightMargin, 0.68 * cm, f"Page {document.page}")
    canvas.restoreState()


def _paragraph(text: str, style_name: str) -> Paragraph:
    return Paragraph(_escape(text), _styles()[style_name])


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "University": ParagraphStyle(
            "University",
            parent=base["Heading1"],
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=18,
            spaceAfter=3,
            textColor=colors.HexColor("#111827"),
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#374151"),
        ),
        "PaperTitle": ParagraphStyle(
            "PaperTitle",
            parent=base["Heading2"],
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#111827"),
        ),
        "MetaLabel": ParagraphStyle(
            "MetaLabel",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#1F2937"),
        ),
        "MetaValue": ParagraphStyle(
            "MetaValue",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#111827"),
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=12,
            spaceAfter=5,
            textColor=colors.HexColor("#111827"),
        ),
        "Instruction": ParagraphStyle(
            "Instruction",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#1F2937"),
        ),
        "QuestionNumber": ParagraphStyle(
            "QuestionNumber",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=12,
            textColor=colors.HexColor("#111827"),
        ),
        "Question": ParagraphStyle(
            "Question",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            alignment=TA_JUSTIFY,
            textColor=colors.HexColor("#111827"),
        ),
        "Marks": ParagraphStyle(
            "Marks",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            alignment=TA_RIGHT,
            textColor=colors.HexColor("#111827"),
        ),
        "Option": ParagraphStyle(
            "Option",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.7,
            leading=11,
            textColor=colors.HexColor("#1F2937"),
        ),
        "QuestionMeta": ParagraphStyle(
            "QuestionMeta",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=7.5,
            leading=9,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#6B7280"),
            spaceBefore=2,
        ),
        "AnswerLabel": ParagraphStyle(
            "AnswerLabel",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#065F46"),
        ),
        "Answer": ParagraphStyle(
            "Answer",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.7,
            leading=12,
            textColor=colors.HexColor("#111827"),
        ),
        "Explanation": ParagraphStyle(
            "Explanation",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#374151"),
        ),
        "Warning": ParagraphStyle(
            "Warning",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            alignment=TA_CENTER,
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#9A3412"),
            backColor=colors.HexColor("#FFF7ED"),
            borderColor=colors.HexColor("#FDBA74"),
            borderWidth=0.5,
            borderPadding=6,
            spaceAfter=8,
        ),
    }


def _format_date(value: object) -> str:
    if isinstance(value, datetime):
        date_value = value
    else:
        try:
            date_value = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except (TypeError, ValueError):
            date_value = datetime.now(timezone.utc)
    return date_value.strftime("%d %b %Y")


def _label(value: object) -> str:
    return str(value or "").replace("_", " ").title()


def _clean_text(value: object) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def _safe_filename(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_") or "paper"


def _escape(value: str) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
